### ISSUE TITLE
HBaseScheme can only serialize strings

### ISSUE THREAD

**Issue by senior** [Cascading/maple#24]
I have an HBase scheme/tap written for a Cascading 2.0 pre-release version that I would love to replace with the HBase tap/scheme in maple.  One issue I'm running into is the code assumes [row keys](https://github.com/Cascading/maple/blob/develop/src/jvm/com/twitter/maple/hbase/HBaseScheme.java#L209)  and [values](https://github.com/Cascading/maple/blob/develop/src/jvm/com/twitter/maple/hbase/HBaseScheme.java#L220) are strings.  I'm using bytes as the key and thrift structures serialized to bytes for the values.

Is there any interest in making the maple HBaseScheme more flexible in this regard?  Looks like the scheme source code just puts the bytes in a tuple.  Maybe the sink code could do the same?

**Comment by azymnis** [comment]
Yes this would definitely be a good fix. We only use the HBaseScheme for sourcing so I have not put much effort into the sinking part.

**Comment by senior** [comment]
I have sent over a pull request (#27) for this.  Let me know if the change is not what you were thinking

**Comment by azymnis** [comment]
I merged it. I have one more thing I want to get out and will release a new version soon.

**Comment by azymnis** [comment]
FYI published in 0.2.4
