### ISSUE TITLE
use org.apache.hadoop.mapreduce

### ISSUE THREAD

**Issue by ehartford** [Cascading/maple#43]
use org.apache.hadoop.mapreduce instead of deprecated org.apache.hadoop.mapred

**Comment by sritchie** [comment]
Probably not going to happen, given that Cascading is stuck on "mapred" for the foreseeable future.

**Comment by ehartford** [comment]
If something is blocking this issue from being resolved, then shouldn't it remain open until the blocking issue is resolved?

Unless you are saying this is an invalid issue to begin with?

**Comment by sritchie** [comment]
I guess I'm saying that @cwensel has made it clear that he doesn't want to use the mapreduce APIs, and prefers to stick with "mapred". Probably makes sense to open an issue at the Cascading issue tracker (https://github.com/cwensel/cascading) so that we can get @cwensel's opinion... I closed this because the maple project isn't going to address this until Cascading has.

**Comment by cwensel** [comment]
there isn't much point in it when a MapReduce replacement is in the works. 

we don't want to support 3 execution models, MR1, MR2, and Tez. MR1 and MR2 are functionally equivalent (just changes in the API), Tez in theory is a step forward. 

we already have to support Hadoop1 and Hadoop2 in tandem in a near future release.

ckw

On Aug 28, 2013, at 9:13 AM, Sam Ritchie notifications@github.com wrote:

> I guess I'm saying that @cwensel has made it clear that he doesn't want to use the mapreduce APIs, and prefers to stick with "mapred". Probably makes sense to open an issue at the Cascading issue tracker (https://github.com/cwensel/cascading) so that we can get @cwensel's opinion... I closed this because the maple project isn't going to address this until Cascading has.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com
