### ISSUE TITLE
JDBCTap fails when trying to write byte arrays

### ISSUE THREAD

**Issue by mishok13** [Cascading/maple#49]
Hi,

I've recently ran into an issue when trying to write byte arrays using JDBCTap (I'm using `bytea` type in PostgreSQL). The issue is almost identical to the one resolved by this [pull request](https://github.com/Cascading/maple/pull/39) but concerns writing instead of reading objects from Postgres. Basically it boils down to the fact that cascading.tuple.Tuple's get method does a cast to Comparable which of course breaks types that don't implement said interface.

I have a [patch](https://github.com/Cascading/maple/pull/48) for this issue, which solves it for me without breaking any of existing code.

Cheers.

**Comment by johnynek** [comment]
I think maple is an end-of-life situation, sorry. Can I suggest you migrate to https://github.com/Cascading/cascading-jdbc ?

**Comment by mishok13** [comment]
@johnynek Ah, indeed. Thanks for the suggestion, cascading-jdbc looks like a good option for us. I'll close the ticket then. 

Cheers!
